[build]
base = "themes/quire-starter-theme"
publish = "site"
command = "npm run build:production"

[context.production.environment]
HUGO_VERSION = "0.55.5"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
base = "themes/quire-starter-theme"
command = "npm run build:preview"

[context.split1.environment]
HUGO_VERSION = "0.55.5"
HUGO_ENV = "production"

[context.deploy-preview]
base = "themes/quire-starter-theme"
command = "npm run build:preview"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.5"

[context.branch-deploy]
base = "themes/quire-starter-theme"
command = "npm run build:preview"

[context.branch-deploy.environment]
HUGO_VERSION = "0.55.5"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://occasional-papers-3.netlify.com/*"
  to = "https://occasional-papers-3.netlify.com/publications/occasional-papers-3/:splat"
  status = 301
  force = true